import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';

import { initializeApp } from "firebase/app";
import { getDatabase, ref, onValue } from "firebase/database";

import LineGraph from "../components/LineGraph";

const inter = Inter({ subsets: ['latin'] })

export default function Home({data, dataObj}) {
  // console.log(data);
  let tempData = data.map(({ temp }) => temp);
  let timeData = data.map(({ time }) => time);
  let humidityData = data.map(({ humidity }) => humidity);
  let brightnessData = data.map(({ brightness }) => brightness);
  // console.log(result);
  
  timeData.forEach((element, index) => {
    console.log();
    const jsEpoch = new Date(element*1000);
    timeData[index] = jsEpoch.toUTCString();
  });

  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Visualising data from Arduino with Firebase</h1>
        <LineGraph id="1" dataset={tempData} labels={timeData} name="Temperature" color="red" />
        <LineGraph id="2" dataset={humidityData} labels={timeData} name="Humidity" color="blue" />
        <LineGraph id="2" dataset={brightnessData} labels={timeData} name="Light Level" color="purple" />
        <div className={styles.description}>

          <h2>All Entries</h2>
          <ul>
            {data.map((item, i) => (
                <li key={i}>
                  <ul>
                    <h3>Entry {i}</h3>
                    
                    <li>
                      Time: {new Date(item.time * 1000).toDateString()} {new Date(item.time * 1000).toTimeString()}
                    </li>

                    <li>
                      Temp: {item.temp}
                    </li>

                    <li>
                      Humidity: {item.humidity}
                    </li>

                    <li>
                      Brightness: {item.brightness}
                    </li>
                  </ul>
                  
                </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
    // TODO: Replace the following with your app's Firebase project configuration
  // See: https://firebase.google.com/docs/web/learn-more#config-object
  const firebaseConfig = {
    // ...
    // The value of `databaseURL` depends on the location of the database
    databaseURL: "https://arduino-plants-default-rtdb.europe-west1.firebasedatabase.app/",
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);

  // const [weatherData, setWeatherData] = useState(0);

  // Initialize Realtime Database and get a reference to the service
  const database = getDatabase(app);
  var localWeatherData = ref(database, 'localWeather/');
  // console.log(localWeatherData);
  // onValue(localWeatherData, (snapshot) => {
  //     const data = snapshot.val();
  //     setWeatherData(data);
  // });
  // https://arduino-plants-default-rtdb.europe-west1.firebasedatabase.app/
  const res = await fetch('https://arduino-plants-default-rtdb.europe-west1.firebasedatabase.app/localWeather.json');
  const data = await res.json();
  // get(child(localWeatherData, '')).then((snapshot) => {
  //   if (snapshot.exists()) {
  //     console.log(snapshot.val());
  //   } else {
  //     console.log("No data available");
  //   }
  // }).catch((error) => {
  //   console.error(error);
  // });

  return {
    props: {
      dataObj : data,
      data : Object.values(data),
    }
  }

}